/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DAO_TRAINING.QuanLyData;
import SQLServerProvider.DBConnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.ir.Flags;
import pojo.item;
/**
 *
 * @author ADMIN
 */
public class frmKiemTra extends javax.swing.JFrame {

    /**
     * Creates new form frmKiemTra
     */
    public frmKiemTra() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    item i = new item();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnNhomNguoi = new javax.swing.ButtonGroup();
        groupRad_KhoiHoc = new javax.swing.ButtonGroup();
        groupRad_HocLuc = new javax.swing.ButtonGroup();
        groupRad_KinhTe = new javax.swing.ButtonGroup();
        pnFirst = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnTrai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        pnNoiDungCauHoi = new javax.swing.JPanel();
        pnCauHoi01 = new javax.swing.JPanel();
        rad_SangTao = new javax.swing.JRadioButton();
        rad_HanhDong = new javax.swing.JRadioButton();
        rad_Logic = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rad_ToChuc = new javax.swing.JRadioButton();
        rad_DaoTao = new javax.swing.JRadioButton();
        rad_DamPhan = new javax.swing.JRadioButton();
        pnCauHoi2 = new javax.swing.JPanel();
        rad_TuNhien = new javax.swing.JRadioButton();
        rad_XaHoi = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        pnCauHoi6 = new javax.swing.JPanel();
        rad_trungLuu = new javax.swing.JRadioButton();
        rad_ThuongLuu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rad_HoanCanhKhoKhan = new javax.swing.JRadioButton();
        pnCauHoi4 = new javax.swing.JPanel();
        rad_TrungBinh = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rad_Kha = new javax.swing.JRadioButton();
        rad_Yeu = new javax.swing.JRadioButton();
        rad_Gioi = new javax.swing.JRadioButton();
        pnTieuDe = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();
        pnMenuTrai = new javax.swing.JPanel();
        btnTinhToan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblKetQuaKyThuat = new javax.swing.JLabel();
        lblKetQuaKhoaHoc = new javax.swing.JLabel();
        lblKetQuaKinhTe = new javax.swing.JLabel();
        lblKetQuaAnNinh = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        pnLasr = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblKetQuan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTimeRun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnFirst.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("CHÀO MỪNG BẠN ĐẾN VỚI PHẦN MỀM TƯ VẤN CHỌN NGÀNH NGHỀ");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("CỦA CHÚNG TÔI");

        javax.swing.GroupLayout pnFirstLayout = new javax.swing.GroupLayout(pnFirst);
        pnFirst.setLayout(pnFirstLayout);
        pnFirstLayout.setHorizontalGroup(
            pnFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFirstLayout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(pnFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnFirstLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel2)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        pnFirstLayout.setVerticalGroup(
            pnFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFirstLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(pnFirst, java.awt.BorderLayout.PAGE_START);

        pnTrai.setBackground(new java.awt.Color(153, 153, 153));

        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Người dùng trả lời hết\ncâu hỏi của  chúng tôi\nbằng cách chọn vào các\ncâu trắc nghiệm.\nKết quả mà bạn sẽ nhận\nđược sẽ  không chính\nxác 100% nhưng sẽ giúp\nbạn một phần nhỏ trong\nviệc đưa ra quyết định\ncủa mình... \n\n    Cảm ơn bạn đã góp\nphần giúp chúng tôi hoàn \nthiện hơn sản phẩm \ncủa mình");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Hướng dẫn :");

        javax.swing.GroupLayout pnTraiLayout = new javax.swing.GroupLayout(pnTrai);
        pnTrai.setLayout(pnTraiLayout);
        pnTraiLayout.setHorizontalGroup(
            pnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTraiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnTraiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTraiLayout.setVerticalGroup(
            pnTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTraiLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnTrai, java.awt.BorderLayout.WEST);

        pnCenter.setBackground(java.awt.SystemColor.activeCaption);
        pnCenter.setLayout(new java.awt.BorderLayout());

        pnNoiDungCauHoi.setLayout(null);

        pnCauHoi01.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        pnCauHoi01.setPreferredSize(new java.awt.Dimension(289, 500));

        groupBtnNhomNguoi.add(rad_SangTao);
        rad_SangTao.setText("Người thích sáng tạo");

        groupBtnNhomNguoi.add(rad_HanhDong);
        rad_HanhDong.setText("Người thích hành động");

        groupBtnNhomNguoi.add(rad_Logic);
        rad_Logic.setText("Người thích công việc suy nghĩ logic ");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Bạn thuộc nhóm người như thế nào ?");

        groupBtnNhomNguoi.add(rad_ToChuc);
        rad_ToChuc.setText("Người thích tổ chức");

        groupBtnNhomNguoi.add(rad_DaoTao);
        rad_DaoTao.setText("Người thích công việc đào tạo");

        groupBtnNhomNguoi.add(rad_DamPhan);
        rad_DamPhan.setText("Người thích đàm phán");

        javax.swing.GroupLayout pnCauHoi01Layout = new javax.swing.GroupLayout(pnCauHoi01);
        pnCauHoi01.setLayout(pnCauHoi01Layout);
        pnCauHoi01Layout.setHorizontalGroup(
            pnCauHoi01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCauHoi01Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCauHoi01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_DaoTao)
                    .addComponent(rad_DamPhan)
                    .addComponent(rad_Logic)
                    .addComponent(rad_HanhDong)
                    .addComponent(rad_ToChuc)
                    .addComponent(rad_SangTao)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54))
        );
        pnCauHoi01Layout.setVerticalGroup(
            pnCauHoi01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCauHoi01Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_SangTao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_Logic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_ToChuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_HanhDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_DamPhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_DaoTao)
                .addGap(246, 246, 246))
        );

        pnNoiDungCauHoi.add(pnCauHoi01);
        pnCauHoi01.setBounds(0, 0, 289, 210);

        pnCauHoi2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        groupRad_KhoiHoc.add(rad_TuNhien);
        rad_TuNhien.setText("Khối khoa học tự nhiên");

        groupRad_KhoiHoc.add(rad_XaHoi);
        rad_XaHoi.setText("Khối khoa học xã hội");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Khối học yêu thích của bạn ?");

        javax.swing.GroupLayout pnCauHoi2Layout = new javax.swing.GroupLayout(pnCauHoi2);
        pnCauHoi2.setLayout(pnCauHoi2Layout);
        pnCauHoi2Layout.setHorizontalGroup(
            pnCauHoi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCauHoi2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnCauHoi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_TuNhien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnCauHoi2Layout.createSequentialGroup()
                        .addGroup(pnCauHoi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rad_XaHoi))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnCauHoi2Layout.setVerticalGroup(
            pnCauHoi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCauHoi2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_TuNhien)
                .addGap(30, 30, 30)
                .addComponent(rad_XaHoi)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pnNoiDungCauHoi.add(pnCauHoi2);
        pnCauHoi2.setBounds(289, 0, 289, 210);

        pnCauHoi6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        groupRad_KinhTe.add(rad_trungLuu);
        rad_trungLuu.setText("Trung lưu");

        groupRad_KinhTe.add(rad_ThuongLuu);
        rad_ThuongLuu.setText("Thượng lưu");

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setText("Bạn thuộc nhóm người như thế nào ?");

        groupRad_KinhTe.add(rad_HoanCanhKhoKhan);
        rad_HoanCanhKhoKhan.setText("Hoàn cảnh khó khăn");

        javax.swing.GroupLayout pnCauHoi6Layout = new javax.swing.GroupLayout(pnCauHoi6);
        pnCauHoi6.setLayout(pnCauHoi6Layout);
        pnCauHoi6Layout.setHorizontalGroup(
            pnCauHoi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCauHoi6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCauHoi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_HoanCanhKhoKhan)
                    .addComponent(rad_ThuongLuu)
                    .addComponent(rad_trungLuu)
                    .addComponent(jLabel9))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnCauHoi6Layout.setVerticalGroup(
            pnCauHoi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCauHoi6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(rad_trungLuu)
                .addGap(18, 18, 18)
                .addComponent(rad_ThuongLuu)
                .addGap(18, 18, 18)
                .addComponent(rad_HoanCanhKhoKhan)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnNoiDungCauHoi.add(pnCauHoi6);
        pnCauHoi6.setBounds(0, 210, 289, 200);

        pnCauHoi4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));

        groupRad_HocLuc.add(rad_TrungBinh);
        rad_TrungBinh.setText("Trung bình");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setText("Học Lực Của Bạn ?");

        groupRad_HocLuc.add(rad_Kha);
        rad_Kha.setText("Khá");

        groupRad_HocLuc.add(rad_Yeu);
        rad_Yeu.setText("Yếu");

        groupRad_HocLuc.add(rad_Gioi);
        rad_Gioi.setText("Giỏi");

        javax.swing.GroupLayout pnCauHoi4Layout = new javax.swing.GroupLayout(pnCauHoi4);
        pnCauHoi4.setLayout(pnCauHoi4Layout);
        pnCauHoi4Layout.setHorizontalGroup(
            pnCauHoi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCauHoi4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnCauHoi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(pnCauHoi4Layout.createSequentialGroup()
                        .addGroup(pnCauHoi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_Gioi)
                            .addComponent(rad_Kha))
                        .addGap(59, 59, 59)
                        .addGroup(pnCauHoi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_Yeu)
                            .addComponent(rad_TrungBinh))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pnCauHoi4Layout.setVerticalGroup(
            pnCauHoi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCauHoi4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(pnCauHoi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_Gioi)
                    .addComponent(rad_TrungBinh))
                .addGap(18, 18, 18)
                .addGroup(pnCauHoi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_Kha)
                    .addComponent(rad_Yeu))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pnNoiDungCauHoi.add(pnCauHoi4);
        pnCauHoi4.setBounds(290, 210, 289, 200);

        pnCenter.add(pnNoiDungCauHoi, java.awt.BorderLayout.CENTER);

        pnTieuDe.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tên của bạn :");

        txtTen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Tuổi               :");

        txtTuoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout pnTieuDeLayout = new javax.swing.GroupLayout(pnTieuDe);
        pnTieuDe.setLayout(pnTieuDeLayout);
        pnTieuDeLayout.setHorizontalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnTieuDeLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTieuDeLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(28, 28, 28)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        pnTieuDeLayout.setVerticalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pnCenter.add(pnTieuDe, java.awt.BorderLayout.PAGE_START);

        pnMenuTrai.setBackground(new java.awt.Color(153, 153, 153));

        btnTinhToan.setBackground(new java.awt.Color(0, 0, 204));
        btnTinhToan.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnTinhToan.setText("BẮT ĐẦU TÍNH KẾT QUẢ");
        btnTinhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhToanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nhóm ngành kĩ thuật :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nhóm ngành kinh tế :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nhóm ngành khoa học :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nhóm ngành an ninh :");

        lblKetQuaKyThuat.setText("_____________");

        lblKetQuaKhoaHoc.setText("___________");

        lblKetQuaKinhTe.setText("___________");

        lblKetQuaAnNinh.setText("___________");

        btnAdd.setBackground(new java.awt.Color(0, 0, 204));
        btnAdd.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAdd.setText("Cung cấp dữ liệu của bạn cho nhà phát triển");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnQuayLai.setBackground(new java.awt.Color(153, 0, 0));
        btnQuayLai.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnQuayLai.setText("TRỞ VỀ TRANG BẮT ĐẦU");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuTraiLayout = new javax.swing.GroupLayout(pnMenuTrai);
        pnMenuTrai.setLayout(pnMenuTraiLayout);
        pnMenuTraiLayout.setHorizontalGroup(
            pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuTraiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTinhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuTraiLayout.createSequentialGroup()
                        .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnMenuTraiLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblKetQuaKinhTe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMenuTraiLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblKetQuaKyThuat, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(pnMenuTraiLayout.createSequentialGroup()
                        .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnMenuTraiLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblKetQuaAnNinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMenuTraiLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblKetQuaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(btnQuayLai, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMenuTraiLayout.setVerticalGroup(
            pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuTraiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnTinhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblKetQuaKyThuat, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblKetQuaKinhTe, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblKetQuaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblKetQuaAnNinh, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pnCenter.add(pnMenuTrai, java.awt.BorderLayout.EAST);

        pnLasr.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Với những gì bạn chọn thì chúng tôi nghĩ bạn hợp với :");

        lblKetQuan.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblKetQuan.setForeground(new java.awt.Color(255, 0, 0));
        lblKetQuan.setText(".............");

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Thời gian thực Thi theo tuần tự :");

        lblTimeRun.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblTimeRun.setForeground(new java.awt.Color(255, 0, 0));
        lblTimeRun.setText("jLabel13");
        lblTimeRun.setEnabled(false);

        javax.swing.GroupLayout pnLasrLayout = new javax.swing.GroupLayout(pnLasr);
        pnLasr.setLayout(pnLasrLayout);
        pnLasrLayout.setHorizontalGroup(
            pnLasrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLasrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLasrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLasrLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblKetQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLasrLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTimeRun, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnLasrLayout.setVerticalGroup(
            pnLasrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLasrLayout.createSequentialGroup()
                .addGroup(pnLasrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(lblKetQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnLasrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimeRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnCenter.add(pnLasr, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhToanActionPerformed
        // TODO add your handling code here:
        DecimalFormat format = new DecimalFormat("0.0000"); 
        Long startTime = Calendar.getInstance().getTimeInMillis();
        if(rad_DaoTao.isSelected())
        {
            i.setNHOMNGUOI(rad_DaoTao.getText());
        }
        else if(rad_Logic.isSelected())
        {
            i.setNHOMNGUOI(rad_Logic.getText());
        }
        else if(rad_ToChuc.isSelected())
        {
            i.setNHOMNGUOI(rad_ToChuc.getText());
        }
        else if(rad_HanhDong.isSelected())
        {
            i.setNHOMNGUOI(rad_HanhDong.getText());
        }
        else if(rad_SangTao.isSelected())
        {
            i.setNHOMNGUOI(rad_SangTao.getText());
        }
        
        //Khối học yêu thích
        if(rad_TuNhien.isSelected())
        {
            i.setKHOIHOCYEUTHICH(rad_TuNhien.getText());
        }
        else if(rad_XaHoi.isSelected())
        {
            i.setKHOIHOCYEUTHICH(rad_XaHoi.getText());
        }
        
        
        //Học lực
        if(rad_Gioi.isSelected())
        {
            i.setHOCLUC(rad_Gioi.getText());
        }
        else if(rad_Kha.isSelected())
        {
            i.setHOCLUC(rad_Kha.getText());
        }
        else if(rad_TrungBinh.isSelected())
        {
            i.setHOCLUC(rad_TrungBinh.getText());
        }
        else if(rad_Yeu.isSelected())
        {
            i.setHOCLUC(rad_Yeu.getText());
        }
        
        //Điều kiện kinh tế
        if(rad_ThuongLuu.isSelected())
        {
            i.setKINHTE(rad_ThuongLuu.getText());
        }
        else if(rad_trungLuu.isSelected())
        {
            i.setKINHTE(rad_trungLuu.getText());
        }
        else if(rad_HoanCanhKhoKhan.isSelected())
        {
            i.setKINHTE(rad_HoanCanhKhoKhan.getText());
        }
        
        double pNhan_KiThuat = (QuanLyData.tinhToanSoNhan("Nhóm ngành kĩ thuật"));
        double pNhomNguoiKT = (QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm ngành kĩ thuật")/pNhan_KiThuat*10000)/10000;
        double pKhoiHocKT = (QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm ngành kĩ thuật")/pNhan_KiThuat*10000)/10000;
        double pKinhTeKT = (QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm ngành kĩ thuật")/pNhan_KiThuat*10000)/10000;
        double pHocLucKT = (QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm ngành kĩ thuật")/pNhan_KiThuat*10000)/10000;
        double kqKT = (pHocLucKT*pKhoiHocKT*pKinhTeKT*pNhomNguoiKT*(pNhan_KiThuat/QuanLyData.tinhTong())*10000)/10000;
        
        if(kqKT==0)
        {
            pNhan_KiThuat=pNhan_KiThuat+4;
            pNhomNguoiKT = ((QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm ngành kĩ thuật")+1)/pNhan_KiThuat*10000)/10000;
            pKhoiHocKT = ((QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm ngành kĩ thuật")+1)/pNhan_KiThuat*10000)/10000;
            pKinhTeKT = ((QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm ngành kĩ thuật")+1)/pNhan_KiThuat*10000)/10000;
            pHocLucKT = ((QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm ngành kĩ thuật")+1)/pNhan_KiThuat*10000)/10000;
            kqKT = (pHocLucKT*pKhoiHocKT*pKinhTeKT*pNhomNguoiKT*(pNhan_KiThuat/QuanLyData.tinhTong())*10000)/10000;
        
        }
        double a = (double) Math.round(kqKT*1000000)/1000000; 
        String s = format.format(a);
        
        String strKQ = s.replace(',', '.');
        lblKetQuaKyThuat.setText(strKQ);
        double kqKiThuatKT = Double.parseDouble(strKQ);
        System.out.println("Kĩ thuật="+kqKiThuatKT);
        

        
        
        //khoa học
        double pNhan_KhoaHoc = (QuanLyData.tinhToanSoNhan("Nhóm ngành khoa học"));
        double pNhomNguoiKH = ((QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm ngành khoa học")/pNhan_KhoaHoc)*10000)/10000;
        double pKhoiHocKH = ((QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm ngành khoa học")/pNhan_KhoaHoc)*10000)/10000;
        double pKinhTeKH = ((QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm ngành khoa học")/pNhan_KhoaHoc)*10000)/10000;
        double pHocLucKH = ((QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm ngành khoa học")/pNhan_KhoaHoc)*10000)/10000;
        double kqKH =(pHocLucKH*pKhoiHocKH*pKinhTeKH*pNhomNguoiKH*(pNhan_KhoaHoc/QuanLyData.tinhTong())*10000)/10000;
        
        if(kqKH==0)
        {
            pNhan_KhoaHoc = pNhan_KhoaHoc+4;
            pNhomNguoiKH = (((QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm ngành khoa học"))+1)/pNhan_KhoaHoc*10000)/10000;
            pKhoiHocKH = (((QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm ngành khoa học")+1)/pNhan_KhoaHoc)*10000)/10000;
            pKinhTeKH = (((QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm ngành khoa học")+1)/pNhan_KhoaHoc)*10000)/10000;
            pHocLucKH = (((QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm ngành khoa học")+1)/pNhan_KhoaHoc)*10000)/10000;
            kqKH =(pHocLucKH*pKhoiHocKH*pKinhTeKH*pNhomNguoiKH*(pNhan_KhoaHoc/QuanLyData.tinhTong())*10000)/10000;
        
        }
        
        double b = (double) Math.ceil(kqKH*1000000)/1000000;
        lblKetQuaKhoaHoc.setText(format.format(b));
        String x = format.format(b);
        
        String strKQKH = x.replace(',', '.');
        double kqKhoaHocKH = Double.parseDouble(strKQKH);
        
        System.out.println("Khoa học="+kqKhoaHocKH);
        
        //kinh tế
        double pNhan_KinhTe = (QuanLyData.tinhToanSoNhan("Nhóm ngành kinh tế"));
        double pNhomNguoiKTe = (QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm ngành kinh tế")/pNhan_KinhTe*10000)/10000;
        double pKhoiHocKTe = (QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm ngành kinh tế")/pNhan_KinhTe*10000)/10000;
        double pKinhTeKTe = (QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm ngành kinh tế")/pNhan_KinhTe*10000)/10000;
        double pHocLucKTe = (QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm ngành kinh tế")/pNhan_KinhTe*10000)/10000;
        double kqKTe = (pNhomNguoiKTe*pKhoiHocKTe*pKinhTeKTe*pHocLucKTe*(pNhan_KinhTe/QuanLyData.tinhTong())*10000)/10000;
        
        if(kqKTe==0)
        {
             pNhan_KinhTe = (QuanLyData.tinhToanSoNhan("Nhóm ngành kinh tế"))+4;
            pNhomNguoiKTe = ((QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm ngành kinh tế")+1)/pNhan_KinhTe*10000)/10000;
            pKhoiHocKTe = ((QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm ngành kinh tế")+1)/pNhan_KinhTe*10000)/10000;
            pKinhTeKTe = ((QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm ngành kinh tế")+1)/pNhan_KinhTe*10000)/10000;
            pHocLucKTe = ((QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm ngành kinh tế")+1)/pNhan_KinhTe*10000)/10000;
            kqKTe = (pNhomNguoiKTe*pKhoiHocKTe*pKinhTeKTe*pHocLucKTe*(pNhan_KinhTe/QuanLyData.tinhTong())*10000)/10000;
        
        }
        
        double d = (double) Math.round(kqKTe*1000000)/1000000;
        String e = format.format(d);
        
        String strKQKT = e.replace(',', '.');
        lblKetQuaKinhTe.setText(strKQKT);
        double kqKinhTeKTe = Double.parseDouble(strKQKT);
        System.out.println("kinh tế="+kqKinhTeKTe);
        
        //an ninh

        double  pNhan_AnNinh = (QuanLyData.tinhToanSoNhan("Nhóm quốc phòng"));
        double  pNhomNguoiAN = ((QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm quốc phòng")/pNhan_AnNinh)*10000)/10000;
        double  pKhoiHocAN = ((QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm quốc phòng"))/pNhan_AnNinh*10000)/10000;
        double  pKinhTeAN = ((QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm quốc phòng")/pNhan_AnNinh)*10000)/10000;
        double  pHocLucAN = ((QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm quốc phòng")/pNhan_AnNinh)*10000)/10000;
        double  kqAN = (pNhomNguoiAN*pHocLucAN*pKhoiHocAN*pKinhTeAN*(pNhan_AnNinh/QuanLyData.tinhTong())*10000)/10000;
        
        if(kqAN==0)
        {
            pNhan_AnNinh = (QuanLyData.tinhToanSoNhan("Nhóm quốc phòng"))+4;
            pNhomNguoiAN = (((QuanLyData.tinhToanXacXuat("NHOMNGUOI",i.getNHOMNGUOI(),"Nhóm quốc phòng")+1)/pNhan_AnNinh)*10000)/10000;
            pKhoiHocAN = (((QuanLyData.tinhToanXacXuat("KHOIHOCYEUTHICH",i.getKHOIHOCYEUTHICH(),"Nhóm quốc phòng"))+1)/pNhan_AnNinh*10000)/10000;
            pKinhTeAN = (((QuanLyData.tinhToanXacXuat("KINHTE",i.getKINHTE(),"Nhóm quốc phòng")+1)/pNhan_AnNinh)*10000)/10000;
            pHocLucAN = (((QuanLyData.tinhToanXacXuat("HOCLUC",i.getHOCLUC(),"Nhóm quốc phòng")+1)/pNhan_AnNinh)*10000)/10000;
            kqAN = (pNhomNguoiAN*pHocLucAN*pKhoiHocAN*pKinhTeAN*(pNhan_AnNinh/QuanLyData.tinhTong())*10000)/10000;
        
        }
        
        
        double f = (double) Math.round(kqAN*1000000)/1000000;
        String g = format.format(f);
        String strKQAN = g.replace(',', '.');
        double kqAnNinhAN = Double.parseDouble(strKQAN);
        lblKetQuaAnNinh.setText(strKQAN);
        System.out.println("an ninh="+kqAnNinhAN);
        
        if(kqKiThuatKT>kqKhoaHocKH && kqKiThuatKT>kqAnNinhAN && kqKiThuatKT>kqKinhTeKTe)
        {
            lblKetQuan.setText("Nhóm ngành kí thuật");
            i.setNGANHCHON("Nhóm ngành kí thuật");
        }
        else
            if(kqKhoaHocKH>kqAnNinhAN && kqKhoaHocKH>kqKiThuatKT &&kqKhoaHocKH>kqKinhTeKTe)
        {
            lblKetQuan.setText("Nhóm ngành khoa học");
            i.setNGANHCHON("Nhóm ngành khoa học");
        }
        else
            if(kqAnNinhAN>kqKinhTeKTe && kqAnNinhAN>kqKiThuatKT && kqAnNinhAN>kqKhoaHocKH)
        {
            lblKetQuan.setText("Nhóm quốc phòng an ninh");
            i.setNGANHCHON("Nhóm quốc phòng an ninh");
        }
        else
            if(kqKinhTeKTe>kqAnNinhAN && kqKinhTeKTe>kqKiThuatKT && kqKinhTeKTe>kqKhoaHocKH)
            {
                lblKetQuan.setText("Nhóm ngành king tế");
                i.setNGANHCHON("Nhóm ngành king tế");
            }
        else
                lblKetQuan.setText("Nhóm quốc phòng an ninh");
        lblKetQuan.enable();
        
        Long finishTime = Calendar.getInstance().getTimeInMillis();
        Long timeRun = finishTime-startTime;
        System.out.println("time ="+timeRun);
        lblTimeRun.setText(""+timeRun);
        lblTimeRun.enable();
        
    }//GEN-LAST:event_btnTinhToanActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            // TODO add your handling code here:
            Connection connection = DBConnection.getConnection();
            Statement statement ;
            int ms  = QuanLyData.tinhTong()+1;
            System.out.println(""+ms);
            String sqlInsert = "INSERT INTO DATA_TRAINING(STT,HOVATEN,TUOI,NHOMNGUOI,KHOIHOCYEUTHICH,HOCLUC,KINHTE,NGANHCHON) " +
                    "VALUES('"+ms+"',N'"+txtTen.getText()+"',"+txtTuoi.getText()+",N'"+i.getNHOMNGUOI()+"',N'"+i.getKHOIHOCYEUTHICH()+"',N'"+i.getHOCLUC()+"',N'"+i.getKINHTE()+"',N'"+i.getNGANHCHON()+"')";
            
            System.out.println(""+i.getNHOMNGUOI());
            
            statement = connection.createStatement();
            int x = statement.executeUpdate(sqlInsert);
            if(x>=1){
                JOptionPane.showMessageDialog(this, "Lưu thành công","THÔNG BÁO", JOptionPane.YES_OPTION);
                txtTen.setText("");
                txtTuoi.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmKiemTra.class.getName()).log(Level.SEVERE, null, ex);
        }
               
               
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        frmTraining frm = new frmTraining();
        frm.show();
        this.hide();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKiemTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKiemTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnTinhToan;
    private javax.swing.ButtonGroup groupBtnNhomNguoi;
    private javax.swing.ButtonGroup groupRad_HocLuc;
    private javax.swing.ButtonGroup groupRad_KhoiHoc;
    private javax.swing.ButtonGroup groupRad_KinhTe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblKetQuaAnNinh;
    private javax.swing.JLabel lblKetQuaKhoaHoc;
    private javax.swing.JLabel lblKetQuaKinhTe;
    private javax.swing.JLabel lblKetQuaKyThuat;
    private javax.swing.JLabel lblKetQuan;
    private javax.swing.JLabel lblTimeRun;
    private javax.swing.JPanel pnCauHoi01;
    private javax.swing.JPanel pnCauHoi2;
    private javax.swing.JPanel pnCauHoi4;
    private javax.swing.JPanel pnCauHoi6;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnFirst;
    private javax.swing.JPanel pnLasr;
    private javax.swing.JPanel pnMenuTrai;
    private javax.swing.JPanel pnNoiDungCauHoi;
    private javax.swing.JPanel pnTieuDe;
    private javax.swing.JPanel pnTrai;
    private javax.swing.JRadioButton rad_DamPhan;
    private javax.swing.JRadioButton rad_DaoTao;
    private javax.swing.JRadioButton rad_Gioi;
    private javax.swing.JRadioButton rad_HanhDong;
    private javax.swing.JRadioButton rad_HoanCanhKhoKhan;
    private javax.swing.JRadioButton rad_Kha;
    private javax.swing.JRadioButton rad_Logic;
    private javax.swing.JRadioButton rad_SangTao;
    private javax.swing.JRadioButton rad_ThuongLuu;
    private javax.swing.JRadioButton rad_ToChuc;
    private javax.swing.JRadioButton rad_TrungBinh;
    private javax.swing.JRadioButton rad_TuNhien;
    private javax.swing.JRadioButton rad_XaHoi;
    private javax.swing.JRadioButton rad_Yeu;
    private javax.swing.JRadioButton rad_trungLuu;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
