/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pojo.item;
import DAO_TRAINING.QuanLyData;

/**
 *
 * @author ADMIN
 */
public class frmTraining extends javax.swing.JFrame {

    
     DefaultTableModel model;
    /**
     * Creates new form frmTraining
     */
    public frmTraining() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenuPhai = new javax.swing.JPanel();
        pnMenuTrai = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        pnDuoi = new javax.swing.JPanel();
        btnBatDau = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMenuPhai.setBackground(new java.awt.Color(153, 153, 153));
        pnMenuPhai.setBorder(new javax.swing.border.MatteBorder(null));
        pnMenuPhai.setName("pnMenu"); // NOI18N

        javax.swing.GroupLayout pnMenuPhaiLayout = new javax.swing.GroupLayout(pnMenuPhai);
        pnMenuPhai.setLayout(pnMenuPhaiLayout);
        pnMenuPhaiLayout.setHorizontalGroup(
            pnMenuPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        pnMenuPhaiLayout.setVerticalGroup(
            pnMenuPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(pnMenuPhai, java.awt.BorderLayout.WEST);

        pnMenuTrai.setBackground(new java.awt.Color(153, 153, 153));
        pnMenuTrai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnMenuTrai.setName("pnNoiDung"); // NOI18N

        btnThoat.setText("Thoáy");

        javax.swing.GroupLayout pnMenuTraiLayout = new javax.swing.GroupLayout(pnMenuTrai);
        pnMenuTrai.setLayout(pnMenuTraiLayout);
        pnMenuTraiLayout.setHorizontalGroup(
            pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMenuTraiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnThoat)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnMenuTraiLayout.setVerticalGroup(
            pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(pnMenuTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnMenuTraiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnThoat)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pnMenuTrai, java.awt.BorderLayout.EAST);

        pnCenter.setName("pnCenter"); // NOI18N
        pnCenter.setLayout(new java.awt.BorderLayout());

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "TÊN", "TUỔI", "NHÓM NGƯỜI", "KHỐI HỌC", "HỌC LỰC", "KINH TẾ", "NGÀNH CHỌN"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        pnCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnDuoi.setBackground(new java.awt.Color(204, 204, 204));

        btnBatDau.setBackground(new java.awt.Color(0, 204, 204));
        btnBatDau.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnBatDau.setText("Bắt đầu kiểm tra");
        btnBatDau.setToolTipText("");
        btnBatDau.setName("btnBatDauTest"); // NOI18N
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });

        btnShow.setBackground(new java.awt.Color(204, 0, 51));
        btnShow.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnShow.setText("Show Dữ Liệu Training");
        btnShow.setName("btnShowAll"); // NOI18N
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDuoiLayout = new javax.swing.GroupLayout(pnDuoi);
        pnDuoi.setLayout(pnDuoiLayout);
        pnDuoiLayout.setHorizontalGroup(
            pnDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDuoiLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnDuoiLayout.setVerticalGroup(
            pnDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDuoiLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnDuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pnCenter.add(pnDuoi, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        
        model = new DefaultTableModel();
        
        model.addColumn("STT");
        model.addColumn("Họ Tên");
        model.addColumn("TUỔI");
        model.addColumn("NHÓM NGƯỜI");
        model.addColumn("KHỐI HỌC");
        model.addColumn("HỌC LỰC");
        model.addColumn("KINH TẾ");
        model.addColumn("NGÀNH CHỌN");
        
        
        ArrayList<item> list;
        list = QuanLyData.getTatCaItem();
        
        //lấy dữ liệu
        for(item data:list){
            model.addRow(data.toArrayAll());
        }
        
        tblData.setModel(model);
//        jTable1.setEnabled(false);
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        // TODO add your handling code here:
        frmKiemTra frm = new frmKiemTra();
        frm.show();
        this.hide();
        
    }//GEN-LAST:event_btnBatDauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTraining().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnThoat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnDuoi;
    private javax.swing.JPanel pnMenuPhai;
    private javax.swing.JPanel pnMenuTrai;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
